name: Docker Publish

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
                       
      - name: Build Docker Image
        run: docker build -t jasminegraph .

      - name: Docker Login
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
      
      - name: Get Timestamp
        id: timestamp
        run: echo "current=$(date +'%Y%m%dT%H%M%S')" >> "${GITHUB_OUTPUT}"

      - name: Docker Push
        run: |
          docker tag jasminegraph ${{secrets.DOCKER_USER}}/jasminegraph:latest
          docker tag jasminegraph ${{secrets.DOCKER_USER}}/jasminegraph:${{ steps.timestamp.outputs.current }}
          docker push ${{secrets.DOCKER_USER}}/jasminegraph:latest
          docker push ${{secrets.DOCKER_USER}}/jasminegraph:${{ steps.timestamp.outputs.current }}
